### ISSUE TITLE
Data Wrangling with Pandas-completed.ipynb

### ISSUE THREAD

**Issue by agpmilli** [kirtanp/ADA-EPFL-2016#1]
Hey,
@kirtanp @tbfang @lemmmr 

I am currently peer grading your ADA homework and I have issue seeing your results for the "Data Wrangling", especially for the titanic exercise. Looks like you didnt defined titanic_raw and it is what you use everywhere in the exercise. Am I right?
(another little thing, next time let the data on your github so we can test it directly with a download :) )

**Comment by tbfang** [comment]
Hey @agpmilli, you're absolutely right!! I deleted my line of code defining `titanic_raw`, and changed it to `titanic`, but didn't re-run everything, so the tables and charts were still there. I definitely should have checked again. For your marking purposes, adding `titanic_raw = pd.read_excel('Data/titanic.xls', 'titanic')` should make everything work again. Hopefully you can still see all the charts and tables in the [github page](https://github.com/kirtanp/ADA-EPFL-2016/blob/master/Lab1/Data%20Wrangling%20with%20Pandas-completed.ipynb)! Your comment about the data in the folder is definitely relevant, and well-taken :)

Thanks for the feedback! Let us know if you have any more questions!

**Comment by agpmilli** [comment]
@tbfang 
Okay, thanks for your fast answer! I add this line and continue my grading :)

**Comment by kirtanp** [comment]
Thanks @agpmilli  for your efforts! May I close this issue since we have a conclusion?

**Comment by agpmilli** [comment]
Sure! I close it! :)
