### ISSUE TITLE
1st notebook comments

### ISSUE THREAD

**Issue by petriinap** [kirtanp/ADA-EPFL-2016#2]
In the Ebola exercise, good that you mentioned the problems with data, but I would still have transfered the dates to datetime objects. Also, it would have made sense to have one column for total deaths and one column for new cases for each date. 

In exercise 4 you forgot to sort the values, but I think you just forgot, so no worries!

**Comment by kirtanp** [comment]
Thanks for your comments @petriinap . I agree with you on both the issues. Both the things did not seem essential for the point of the exercise but I agree that we should have done them anyways since they wouldn't have taken a lot of time.

Yeah, we did forget . Sorry about that!
