### ISSUE TITLE
Peer review HW2

### ISSUE THREAD

**Issue by paulnicolet** [kirtanp/ADA-EPFL-2016#3]
Nice work, all parts of the problems are addressed. I have maybe one small suggestion, you should maybe avoid this kind of block : 
`#First master semester df
first_row = df.groupby('Nom Prénom').first()
first_row.rename(columns={'year':'first_year', 'semester':'first_semester'}, inplace=True)
first_row = first_row[['Civilité','first_year','first_semester','Spécialisation']]
first_row.reset_index(inplace=True)`
which in not really explicit, try maybe to split it up in more subparts.

**Comment by kirtanp** [comment]
Thank you for the suggestion. We'll be sure to keep that in mind next time.
